-- ==============================================================
-- RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
-- Version: 2020.1
-- Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity hardware_accelerator is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst_n : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    IN_r_TDATA : IN STD_LOGIC_VECTOR (31 downto 0);
    IN_r_TVALID : IN STD_LOGIC;
    IN_r_TREADY : OUT STD_LOGIC;
    IN_r_TKEEP : IN STD_LOGIC_VECTOR (3 downto 0);
    IN_r_TLAST : IN STD_LOGIC_VECTOR (0 downto 0);
    OUT_r_TDATA : OUT STD_LOGIC_VECTOR (31 downto 0);
    OUT_r_TVALID : OUT STD_LOGIC;
    OUT_r_TREADY : IN STD_LOGIC;
    OUT_r_TKEEP : OUT STD_LOGIC_VECTOR (3 downto 0);
    OUT_r_TLAST : OUT STD_LOGIC_VECTOR (0 downto 0) );
end;


architecture behav of hardware_accelerator is 
    attribute CORE_GENERATION_INFO : STRING;
    attribute CORE_GENERATION_INFO of behav : architecture is
    "hardware_accelerator,hls_ip_2020_1,{HLS_INPUT_TYPE=cxx,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020-clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=2.552000,HLS_SYN_LAT=21,HLS_SYN_TPT=none,HLS_SYN_MEM=0,HLS_SYN_DSP=0,HLS_SYN_FF=11,HLS_SYN_LUT=113,HLS_VERSION=2020_1}";
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_A : STD_LOGIC_VECTOR (3 downto 0) := "1010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";

    signal ap_rst_n_inv : STD_LOGIC;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (2 downto 0) := "001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal IN_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln22_fu_80_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal OUT_r_TDATA_blk_n : STD_LOGIC;
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal i_fu_86_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal i_reg_116 : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_OUT_data_V_U_apdone_blk : STD_LOGIC;
    signal ap_block_state2 : BOOLEAN;
    signal ap_block_state2_io : BOOLEAN;
    signal i_0_reg_69 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (2 downto 0);
    signal regslice_both_IN_data_V_U_apdone_blk : STD_LOGIC;
    signal IN_r_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal IN_r_TVALID_int : STD_LOGIC;
    signal IN_r_TREADY_int : STD_LOGIC;
    signal regslice_both_IN_data_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN_keep_V_U_apdone_blk : STD_LOGIC;
    signal IN_r_TKEEP_int : STD_LOGIC_VECTOR (3 downto 0);
    signal regslice_both_IN_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN_keep_V_U_ack_in : STD_LOGIC;
    signal regslice_both_IN_last_V_U_apdone_blk : STD_LOGIC;
    signal IN_r_TLAST_int : STD_LOGIC_VECTOR (0 downto 0);
    signal regslice_both_IN_last_V_U_vld_out : STD_LOGIC;
    signal regslice_both_IN_last_V_U_ack_in : STD_LOGIC;
    signal OUT_r_TDATA_int : STD_LOGIC_VECTOR (31 downto 0);
    signal OUT_r_TVALID_int : STD_LOGIC;
    signal OUT_r_TREADY_int : STD_LOGIC;
    signal regslice_both_OUT_data_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUT_keep_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUT_keep_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUT_keep_V_U_vld_out : STD_LOGIC;
    signal regslice_both_OUT_last_V_U_apdone_blk : STD_LOGIC;
    signal regslice_both_OUT_last_V_U_ack_in_dummy : STD_LOGIC;
    signal regslice_both_OUT_last_V_U_vld_out : STD_LOGIC;

    component regslice_both IS
    generic (
        DataWidth : INTEGER );
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        data_in : IN STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_in : IN STD_LOGIC;
        ack_in : OUT STD_LOGIC;
        data_out : OUT STD_LOGIC_VECTOR (DataWidth-1 downto 0);
        vld_out : OUT STD_LOGIC;
        ack_out : IN STD_LOGIC;
        apdone_blk : OUT STD_LOGIC );
    end component;



begin
    regslice_both_IN_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN_r_TDATA,
        vld_in => IN_r_TVALID,
        ack_in => regslice_both_IN_data_V_U_ack_in,
        data_out => IN_r_TDATA_int,
        vld_out => IN_r_TVALID_int,
        ack_out => IN_r_TREADY_int,
        apdone_blk => regslice_both_IN_data_V_U_apdone_blk);

    regslice_both_IN_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN_r_TKEEP,
        vld_in => IN_r_TVALID,
        ack_in => regslice_both_IN_keep_V_U_ack_in,
        data_out => IN_r_TKEEP_int,
        vld_out => regslice_both_IN_keep_V_U_vld_out,
        ack_out => IN_r_TREADY_int,
        apdone_blk => regslice_both_IN_keep_V_U_apdone_blk);

    regslice_both_IN_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN_r_TLAST,
        vld_in => IN_r_TVALID,
        ack_in => regslice_both_IN_last_V_U_ack_in,
        data_out => IN_r_TLAST_int,
        vld_out => regslice_both_IN_last_V_U_vld_out,
        ack_out => IN_r_TREADY_int,
        apdone_blk => regslice_both_IN_last_V_U_apdone_blk);

    regslice_both_OUT_data_V_U : component regslice_both
    generic map (
        DataWidth => 32)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => OUT_r_TDATA_int,
        vld_in => OUT_r_TVALID_int,
        ack_in => OUT_r_TREADY_int,
        data_out => OUT_r_TDATA,
        vld_out => regslice_both_OUT_data_V_U_vld_out,
        ack_out => OUT_r_TREADY,
        apdone_blk => regslice_both_OUT_data_V_U_apdone_blk);

    regslice_both_OUT_keep_V_U : component regslice_both
    generic map (
        DataWidth => 4)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN_r_TKEEP_int,
        vld_in => OUT_r_TVALID_int,
        ack_in => regslice_both_OUT_keep_V_U_ack_in_dummy,
        data_out => OUT_r_TKEEP,
        vld_out => regslice_both_OUT_keep_V_U_vld_out,
        ack_out => OUT_r_TREADY,
        apdone_blk => regslice_both_OUT_keep_V_U_apdone_blk);

    regslice_both_OUT_last_V_U : component regslice_both
    generic map (
        DataWidth => 1)
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst_n_inv,
        data_in => IN_r_TLAST_int,
        vld_in => OUT_r_TVALID_int,
        ack_in => regslice_both_OUT_last_V_U_ack_in_dummy,
        data_out => OUT_r_TLAST,
        vld_out => regslice_both_OUT_last_V_U_vld_out,
        ack_out => OUT_r_TREADY,
        apdone_blk => regslice_both_OUT_last_V_U_apdone_blk);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst_n_inv = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    i_0_reg_69_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_logic_1 = OUT_r_TREADY_int))) then 
                i_0_reg_69 <= i_reg_116;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                i_0_reg_69 <= ap_const_lv4_0;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_OUT_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_0 = IN_r_TVALID_int)))) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                i_reg_116 <= i_fu_86_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln22_fu_80_p2, ap_CS_fsm_state3, regslice_both_OUT_data_V_U_apdone_blk, ap_block_state2_io, IN_r_TVALID_int, OUT_r_TREADY_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_OUT_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_0 = IN_r_TVALID_int)))) and (icmp_ln22_fu_80_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_OUT_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_0 = IN_r_TVALID_int)))) and (icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state3) and (ap_const_logic_1 = OUT_r_TREADY_int))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when others =>  
                ap_NS_fsm <= "XXX";
        end case;
    end process;

    IN_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, icmp_ln22_fu_80_p2, IN_r_TVALID_int)
    begin
        if (((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            IN_r_TDATA_blk_n <= IN_r_TVALID_int;
        else 
            IN_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    IN_r_TREADY_assign_proc : process(IN_r_TVALID, regslice_both_IN_data_V_U_ack_in)
    begin
        if (((ap_const_logic_1 = IN_r_TVALID) and (regslice_both_IN_data_V_U_ack_in = ap_const_logic_1))) then 
            IN_r_TREADY <= ap_const_logic_1;
        else 
            IN_r_TREADY <= ap_const_logic_0;
        end if; 
    end process;


    IN_r_TREADY_int_assign_proc : process(ap_CS_fsm_state2, icmp_ln22_fu_80_p2, regslice_both_OUT_data_V_U_apdone_blk, ap_block_state2_io, IN_r_TVALID_int)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_OUT_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_0 = IN_r_TVALID_int)))) and (icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            IN_r_TREADY_int <= ap_const_logic_1;
        else 
            IN_r_TREADY_int <= ap_const_logic_0;
        end if; 
    end process;


    OUT_r_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state2, icmp_ln22_fu_80_p2, ap_CS_fsm_state3, OUT_r_TREADY_int)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state3) or ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            OUT_r_TDATA_blk_n <= OUT_r_TREADY_int;
        else 
            OUT_r_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;

    OUT_r_TDATA_int <= std_logic_vector(unsigned(IN_r_TDATA_int) + unsigned(ap_const_lv32_FF));
    OUT_r_TVALID <= regslice_both_OUT_data_V_U_vld_out;

    OUT_r_TVALID_int_assign_proc : process(ap_CS_fsm_state2, icmp_ln22_fu_80_p2, regslice_both_OUT_data_V_U_apdone_blk, ap_block_state2_io, IN_r_TVALID_int)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_OUT_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_0 = IN_r_TVALID_int)))) and (icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            OUT_r_TVALID_int <= ap_const_logic_1;
        else 
            OUT_r_TVALID_int <= ap_const_logic_0;
        end if; 
    end process;

    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);

    ap_block_state2_assign_proc : process(icmp_ln22_fu_80_p2, regslice_both_OUT_data_V_U_apdone_blk, IN_r_TVALID_int)
    begin
                ap_block_state2 <= ((regslice_both_OUT_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_0 = IN_r_TVALID_int)));
    end process;


    ap_block_state2_io_assign_proc : process(icmp_ln22_fu_80_p2, OUT_r_TREADY_int)
    begin
                ap_block_state2_io <= ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_0 = OUT_r_TREADY_int));
    end process;


    ap_done_assign_proc : process(ap_CS_fsm_state2, icmp_ln22_fu_80_p2, regslice_both_OUT_data_V_U_apdone_blk, ap_block_state2_io, IN_r_TVALID_int)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_OUT_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_0 = IN_r_TVALID_int)))) and (icmp_ln22_fu_80_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_start = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln22_fu_80_p2, regslice_both_OUT_data_V_U_apdone_blk, ap_block_state2_io, IN_r_TVALID_int)
    begin
        if ((not(((ap_const_boolean_1 = ap_block_state2_io) or (regslice_both_OUT_data_V_U_apdone_blk = ap_const_logic_1) or ((icmp_ln22_fu_80_p2 = ap_const_lv1_0) and (ap_const_logic_0 = IN_r_TVALID_int)))) and (icmp_ln22_fu_80_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;


    ap_rst_n_inv_assign_proc : process(ap_rst_n)
    begin
                ap_rst_n_inv <= not(ap_rst_n);
    end process;

    i_fu_86_p2 <= std_logic_vector(unsigned(i_0_reg_69) + unsigned(ap_const_lv4_1));
    icmp_ln22_fu_80_p2 <= "1" when (i_0_reg_69 = ap_const_lv4_A) else "0";
end behav;
